### ISSUE TITLE
Requirements parsing error on some non-normalized spellings in version selection

### ISSUE THREAD

**Issue by tserg** [pypa/pip-audit#464]
This issue was migrated from `gh-action-pip-audit`, since the bug being reported isn't in the action itself.

Upstream tracking: https://github.com/pypa/packaging/issues/653

---

Running the following .yml file results in the following error. I am currently trying to troubleshoot an error flagged by `pip-audit` for [`setuptools`](https://github.com/pypa/pip-audit/pull/454) in the CI environment, and it is likely that `setuptools` is getting flagged by `pip-audit` still, before running into this error.
```
jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run pip-audit
        uses: pypa/gh-action-pip-audit@v1.0.4
        with:
          inputs: requirements-dev.txt
          ignore-vulns: PYSEC-2021-427
```

```
Traceback (most recent call last):
  File "/home/runner/work/_actions/pypa/gh-action-pip-audit/v1.0.4/action.py", line 138, in <module>
    with open("/tmp/pip-audit-output.txt", "r") as io:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-audit-output.txt'
```
