### ISSUE TITLE
[QUESTION] Can I anayze the dependencies in [project.optional-dependencies]?

### ISSUE THREAD

**Issue by albertodiazdorado** [pypa/pip-audit#766]
### Pre-submission checks

- [X] I am **not** reporting a new vulnerability or requesting a new vulnerability identifier. These **must** be reported or managed via upstream dependency sources or services, not this repository.
- [X] I agree to follow the [PSF Code of Conduct](https://www.python.org/psf/conduct/).
- [X] I have looked through the open issues for a duplicate request.

### What's the problem this feature will solve?

_Disclaimer: This is only a question. I looked for a slack or discord space but could not find any, hence I am coming here. Please let me know if there's a better way of asking questions._

Is it possible, somehow, to have `pip-audit` scan not only the dependencies of my project as per `pyproject.toml`
```toml
[project]
dependencies = [
  # ...
]
```

But also include my dev dependencies?
```toml
[project.optional-dependencies]
dev = [
  # ...
]
```

For reference, tools like `liccheck` (for license checking) allow users to include dev dependencies in the analysis like this:
```toml
[tool.liccheck]
authorized_licenses = [
    "bsd",
    "mit",
]
dependencies = true
optional_dependencies = ["dev"]
```

### Describe the solution you'd like

I'd love to be able to include dev dependencies in my scans
